image:
  file: .gitpod.Dockerfile
tasks:
  - name: Terminal
    command: |
      bash
# Ports to expose on workspace startup
ports:
  - port: 23000
    onOpen: open-preview
  - port: 22
    visibility: public
